### ISSUE TITLE
Convert HGVS to Ref/Alt Alleles compatible for VCF format

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#243]
Originally reported by: **Fong Chun Chan (Bitbucket: [fongchun](http://bitbucket.org/fongchun), GitHub: [tinyheero](http://github.com/tinyheero))**

----------------------------------------

Hi,

It would be a great feature to have the functionality to parse a HGVS string and return the corresponding Ref/Alt alleles that is compatible for a VCF format. This is trivial for SNPs, but for deletions the string doesn't contain the reference allele. For instance,

NM_000059.3:c.8332-1603delT

The reference allele, in VCF format, should be GT. But the 5' flanking G base is not encoded in the HGVS string. Without a database to query, it's not possible to know the reference allele. This question is analogous to what was asked here - https://www.biostars.org/p/117873/

Thanks,

Fong

----------------------------------------
- Bitbucket: https://bitbucket.org/biocommons/hgvs/issue/243

**Comment by davmlaw** [comment]
Now that there's  ```seq_fetcher.fetch_seq``` it's easy to get the reference bases, however I looked at this and saw 2 more issues:

* Converting from contigs to chromosomes (eg NC_000001.10 -> "chr1")
* Variant normalisation

### Contigs to chromosomes

I'm not familiar enough with seqrepo or UTA to know if this is available.

You could parse files such as these: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.38_GRCh38.p12/GCF_000001405.38_GRCh38.p12_assembly_report.txt and then look up between "RefSeq-Accn" and "UCSC-style-name"

### Variant normalisation

VCF (at least the standards according to [VT](https://genome.sph.umich.edu/wiki/Vt#Normalization) is left aligned, while HGVS is right aligned.

Example

```
2:209010777 GC>G - which overlaps with NM_005210.3:c.10-38del
g. format => SequenceVariant(ac=NC_000002.11, type=g, posedit=209010782del)
```

The reason the coordinates are different is because the reference is "GCCCCC" - so GC>G means one of the C's was deleted, and which one you store is convention. HGVS is right aligned, while VT left aligns them.

Now, the easiest thing to do is just write out the variant and then run it through VT normalise. That's fine for my program where I'm already piping stuff to VT - but is it an acceptable solution for a library?

**Comment by reece** [comment]
Dave- Neither of these are issues with hgvs. Please consider using hgvs-discuss or the litter channel for questions. 

See bioutils.assemblies.get_assembly for chromosome names.

**Comment by davmlaw** [comment]
Er, I think my comments are directly related to the implementation of "converting HGVS to ref/alt alleles for VCF records" (this issue) which you said was a good idea over 3 years ago, but as far as I know, has not been implemented yet.

**Comment by reece** [comment]
Whoops. You're right. I was answering on my phone where your comment was out of context. I agree. Sorry about that. Reopening.

Relevant: there's a script in misc/ to add hgvs to vcf. See #41.

Within hgvs, let's use the existing normalize code, which takes a direction argument, rather than incurring new dependency.
