### ISSUE TITLE
stringified hgvs variants are not using the c.BASE(s)= nomenclature when using 1.0.1post3

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [biocommons/hgvs#424]
Hi Reece and Meng

The previous version of hgvs that I used (1.0.0a1) correctly displayed variants where posedit.edit.alt was equivalent to posedit.edit.ref as Reference:type.PositionBases= e.g. NC_000017.11:g.50198002C= or NM_000088.3:c.589G=.

Certainly with respect to genomic variants (I have not tested transcript variants, 0.1.0post1 has reverted back to using NC_000017.11:g.50198002= . Please can you put behaviour back to the way it was in the 1.0.0a1 release, particularly because I believe that HGVS guidelines would recommend that the reference bases are displayed.

Thanks

Pete

**Comment by reece** [comment]
Sorry about this, Pete. I'm flabbergasted -- I was nearly certain that we had a test for this when we addressed it previously.

**Comment by PeteCausey-Freeman** [comment]
No problem. 

Thanks 
________________________________________

**Comment by icebert** [comment]
I recall what causes this. I added the max_ref_length in formatter, which was set to be 0 by default. This leads to the missing of ref in ident variants. I just realize that this should not be applied to ident variant and I'll fix this.

**Comment by reece** [comment]
@PeteCausey-Freeman , @meng: I'd like to discuss how this should work. The upshot is that I think we should leave the code as-is, but I want your opinions. (Sorry Meng -- I see that you already submitted a PR.)

First, the cause (for Peter): We recently added a configuration parameter, max_ref_length, that limits the size of the deleted reference sequence displayed for del and delins. Since the deleted sequence is always implied by the reference, it's always legal to omit it. Adding the deleted sequence is particularly useful for relatively small changes. That is, we're happy to look at delACGinsTAGCAC, but less happy if the del sequence is long. We made the default max_ref_length = 0, so that the del sequence is not shown by default. This issue for identity variants occurs because the stringification for identity variants uses the same reference sequence length. With the current code, you can do this:

```Python
>>> v = hp.parse_hgvs_variant("NC_000017.11:g.50198002C=")

# by default:
>>> v.format()
u'NC_000017.11:g.50198002='

# one-time format with custom config:
>>> v.format(conf={"max_ref_length": 10})
u'NC_000017.11:g.50198002C='

# change the global setting
>>> hgvs.global_config.formatting.max_ref_length = 5
>>> v.format()
u'NC_000017.11:g.50198002C='
>>> str(v)
'NC_000017.11:g.50198002C='
```

In reviewing [the VarNomen guidelines for "no change" variants](http://varnomen.hgvs.org/bg-material/consultation/svd-wg001/), there are examples with sequence (`g.11890634G=`, `c.123G=`) and without (`NM_001849.3:c.1_*1=`, `LRG_476:g.4950_39800=`). 

Rationale for keeping the code as-is:
* Consistency: the rule for reference sequence, whether no change" or for a del, should be consistent.
* Omitting the sequence is permitted by the spec.
* It's quite easy for users to change.

So, for these reasons, I'd like to keep the code unchanged. As frequent users, I'd like your input.

**Comment by icebert** [comment]
Hi Reece, I agree with you. I think it's better to keep the formatter behaver consistent among different variants types as long as it doesn't conflict with hgvs nomenclature spec.

**Comment by Akeeeeshi** [comment]
As requested by Reece: Reposting this issue on here about whether sequence is required for "no change" variants.

```
In [29]: parser.parse_hgvs_variant('NM_001206924.1:c.217=')

HGVSParseError Traceback (most recent call last)
...
HGVSParseError: NM_001206924.1:c.217=: char 20: expected one of '?', '_', 'con', 'copy', 'del', 'dup', 'ins', 'inv', or a digit
```

**Comment by reece** [comment]
@Akeeeeshi Thanks. Actually, I already cross-referenced your issue. I was really asking whether you had any opinion about the the discussion above.

**Comment by reece** [comment]
Based on the conversation above, I added tests to ensure that we can parse with and without sequence for no-change variants, and that we generate variants without sequence on formatting (by default -- actual result depends on max_ref_length).
