### ISSUE TITLE
Trouble Parsing Variant

### ISSUE THREAD

**Issue by Akeeeeshi** [biocommons/hgvs#430]
Was suprised that this variant specified by c. failed to parse. Any thoughts? I'm new to this package to I'm not sure if there are some semantics I am missing out on. 

`In [29]: parser.parse_hgvs_variant('NM_001206924.1:c.217=')`
---------------------------------------------------------------------------
`HGVSParseError                            Traceback (most recent call last)`
...
`HGVSParseError: NM_001206924.1:c.217=: char 20: expected one of '?', '_', 'con', 'copy', 'del', 'dup', 'ins', 'inv', or a digit`

**Comment by reece** [comment]
The issue is that the community (and, with some lag, the hgvs package) has gone both ways about whether sequence is required sequence is required for "no change" variants. 

This is related to #424, which we'll fix very shortly. Although that issue is about stringifcation, @icebert's PR also addresses parsing. 

Since you raised the topic, would you please see and respond to the request for comments in #424 today? I will probably proceed as I implied there if I don't receive further comment.

ETA to fix is early next week.

**Comment by reece** [comment]
Closed with #424 -- see comments there.
Please note that this is for 1.0 only -- in previous issue, you were using 0.4, which is not going to be maintained.
