### ISSUE TITLE
covert hgvs g. notation to c. notation with Ensembl transcripts

### ISSUE THREAD

**Issue by yujiang02** [biocommons/hgvs#433]
Hi,

I just tried to use this hgvs tool to perform some conversion between hgvs g. notation and c. notation. I am using the ensembl transcripts instead of refSeq. I tried with the example provided in https://github.com/biocommons/hgvs. However, this one seems only gave RefSeq transcripts c. notation. Is there any example or document for using Ensembl transcripts?

Thanks,
Yu

**Comment by reece** [comment]
Hi Yu-

Only some functions of hgvs + UTA will work with Ensembl transcripts. The limitation is really with UTA and not hgvs itself.

There are several issues. The first is that it's fairly hard to get the data I need for UTA from Ensembl, and therefore I don't do it very often. UTA is currently based on Ensembl 79. The second historical reason is that their fasta files used to have unversioned sequences. That means that the same (unversioned) accession was often associated with multiple distinct sequences over time, which violates an assumption in the code that accessions are associated with exactly one sequence. (Ensembl now versions accessions in their fasta files.) Finally, c_to_p requires a table of ENST-ENSP pairs, which is currently unpopulated for Ensembl. So, although hgvs works with Ensembl in principle (and has in the past), the combination is currently unsupported.

For the record, parsing and normalization work. And projecting variants between c and g works *but only for unversioned transcripts, because that's all that was available at the time*.

I'll close this issue in favor of biocommons/uta#207.

-Reece

**Comment by davmlaw** [comment]
Hi, I recently commented on another HGVS Ensembl issue you may find it useful

https://github.com/biocommons/hgvs/issues/621#issuecomment-1477317577
