### ISSUE TITLE
Make checking coordinate boundaries optional

### ISSUE THREAD

**Issue by ralonso-igenomix** [biocommons/hgvs#437]
Hello
when I run this code:
import hgvs.parser
import hgvs
import hgvs.assemblymapper
import hgvs.dataproviders.uta

hp = hgvs.parser.Parser()
hdp = hgvs.dataproviders.uta.connect()
variantmapper = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name="GRCh37")

cHGVS="NM_000518.4:c.-130C>T"
var_c1 = hp.parse_hgvs_variant(cHGVS)
var_g1 = variantmapper.c_to_g(var_c1); 
var_g1

It gives me this exception:
HGVSError: The given coordinate is outside the bounds of the reference sequence.

But if I go to the variation reporter (https://www.ncbi.nlm.nih.gov/variation/tools/reporter) I get a good result, this one:
NC_000011.9:g.5248381A=

Best regards

**Comment by icebert** [comment]
This is because the CDS of NM_000518.4 is from 51 to 494 of the transcript sequence (https://www.ncbi.nlm.nih.gov/nuccore/NM_000518.4). Thus, the position range for 5' UTR should be -50 to -1. Variation reporter does not check the positions. The hgvs will check the range of variants positions before mapping and perform several other validations of the variant.

**Comment by ralonso-igenomix** [comment]
So, in case I want that position, is it possible with hgvs library? or should I do my own calculations? Maybe it would be useful to pass a flag as argument to not do this kind of check, so I could get the position any way.

**Comment by PeteCausey-Freeman** [comment]
There is a way to map this variant description
Instead of starting with NM_000518.4:c.-130C>T, you can use equivalent description NM_000518.4:c.-50-81C>T (With the caveat that none of these descriptions are HGVS compliant because they specify a position outside the boundaries the transcript).

use evm.c_to_n followed by evm.t_to_g. This should get you to HGVS compliant description C_000011.10:g.5227152C>A. I have not run the code on the command line, but see this link.

[https://variantvalidator.org/variantvalidation/?variant=NM_000518.4%3Ac.-50-81C%3ET&primary_assembly=GRCh38&alignment=splign](url)

**Comment by reece** [comment]
On Thu, May 18, 2017 at 1:28 AM, ralonso-igenomix <notifications@github.com>
wrote:

> So, in case I want that position, is it possible with hgvs library? or
> should I do my own calculations? Maybe it would be useful to pass a flag as
> argument to not do this kind of check, so I could get the position any way.


I like that suggestion.

With the exception of intronic coordinates, which we support for practical
and historical reasons, I hope that we steer people away from defining
variation beyond the bounds of the sequence. Such residues don't exist in
the coordinate system and the behavior should be considered ill-defined.

-Reece

**Comment by reece** [comment]
I started to implement this, but hit a snag. Validation checks the ref nucleotides. It's easy enough to disable the bounds check itself, but it's significant work and ugly to disable ref sequence validation when out of bounds. This needs rethinking. Reece has a patch locally.

**Comment by reece** [comment]
Test case provided by Invitae:

- Parse `NR_003051.3:n.-19_-18insACT`
- Project to genome
- Normalize on genome
- Project back to transcript
- Expected results is `NR_003051.3:n.-21_-19dup`
