### ISSUE TITLE
padding of nucleotide sequences always raises Exception

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#460]
From @ianfab:

I encountered the issue when subclassing the data provider interface, but when using UTA I could not easily find an example where len(tx_seq_to_translate) % 3 != 0 is satisfied, so the code line that causes the issue seems to be called only rarely.

To find examples, I used the following query for UTA:

```
select tx_ac, alt_ac, cds_start_i, cds_end_i, (cds_end_i - cds_start_i) % 3
from tx_def_summary_v
where (cds_end_i - cds_start_i) % 3 != 0
limit 10;
```

With the help of these results I was able to reproduce the TypeError with, e.g.:

```
import hgvs
import hgvs.parser
import hgvs.dataproviders.uta
import hgvs.assemblymapper

hgvsparser = hgvs.parser.Parser()
hdp = hgvs.dataproviders.uta.connect()
am = hgvs.assemblymapper.AssemblyMapper(hdp)

var_c = hgvsparser.parse_hgvs_variant('NM_002537.3:c.250del')
var_p = am.c_to_p(var_c)
```

**Comment by reece** [comment]
While creating the tests for this bug, I discovered this:

```
In [1]: var_c = hgvsparser.parse_hgvs_variant('NM_002537.3:c.250del')

In [2]: var_p = am37.c_to_p(var_c)

In [3]: var_p
Out[3]: SequenceVariant(ac=NP_002528.1, type=p, posedit=None)

In [4]: str(var_p)
Out[4]: 'NP_002528.1:p.?'

```

I can't see why c.250del would ever give a p.? variant.
I'm going to put this on the shelf for a moment until I can investigate. 
If this is a new bug, it may make sense to merge 460-fix-padding into master and then file a new bug.

**Comment by ianfab** [comment]
@reece 
I had a look at the issue with the p.? variant, and found that there are a lot of stop codons in the translated reference sequence when checking it at https://github.com/biocommons/hgvs/blob/234f92e8b0933671b2e129703576c3204ad29748/hgvs/variantmapper.py#L336 during debugging. I then found that there is a programmed ribosomal frameshift in the translation of this transcript (see https://www.ncbi.nlm.nih.gov/nuccore/669250888). So I guess that this could be the reason for the issue, and if so it is perhaps hard to fix this.

**Comment by ianfab** [comment]
@reece 
I am pretty sure now that the translational frameshift mentioned in my previous comment is the reason why `NM_002537.3:c.250del` results in a `p.?` variant. I checked several transcripts in the results list from the query in the initial post and all of them have a translational frameshift, and mapping results in `p.?`.

Using ensembl data the mapping worked for me, since they solve the issue by the introduction of "frameshift introns", see, e.g., [ENST00000326005](grch37.ensembl.org/Homo_sapiens/Transcript/Summary?t=ENST00000326005) which corresponds to [NM_002537](https://www.ncbi.nlm.nih.gov/nuccore/669250888).

As far as I can see, no information about translational frameshifts can be found in UTA, so there perhaps is no way to fix this issue in the code without changes to the database.

In principle, the two bugs regarding the padding and the translational frameshifts are unrelated, but they always occur together when using UTA data, because the length of the coding sequence only differs from multiples of 3 if a translational frameshift occurs (although there might be other rare cases where it is not related to a frameshift, but I could not find an example yet).

**Comment by reece** [comment]
@ianfab Sorry for dropping this for so long.

I agree with your analysis and appreciate you debugging the issue.

UTA and hgvs don't understand translational frameshifts, so there's no way this will work right now.

I'm going to close this as won't fix.
