### ISSUE TITLE
Wrong normalization result

### ISSUE THREAD

**Issue by ianfab** [biocommons/hgvs#464]
Running `print(hn.normalize(hp.parse_hgvs_variant('NC_000001.10:g.1647893delinsCTTTCTT')))`
in the hgvs-shell resulted in `NC_000001.10:g.1647900dup`, which looks incorrect since the length of the inserted sequence does not match. If I am not mistaken, it should be `NC_000001.10:g.1647894_1647899dup` (or `NC_000001.10:g.1647893_1647894insTTTCTT`).

**Comment by reece** [comment]
Thanks, @ianfab. I agree, this is a bug.

@icebert Do you have a moment to look at this? It'll probably be more transparent to you than to me.

**Comment by icebert** [comment]
The correct normalization result should be `NC_000001.10:g.1647895_1647900dup`. I will find out how this bug happens.

**Comment by icebert** [comment]
I find out this is caused by the share of start and end position instance when the start and end is the same. In hgvs parser, when the start and end is same, they will use the same instance. Thus, when changing the end position of such variants in the normalizer, the start position will also be changed. This leads to this bug.

Example code:
```python
import hgvs
import hgvs.parser
import hgvs.normalizer
import hgvs.dataproviders.uta

hdp = hgvs.dataproviders.uta.connect()

hp = hgvs.parser.Parser()

hn = hgvs.normalizer.Normalizer(hdp)

var_g = 'NC_000001.10:g.1647893delinsCTTTCTT'

var = hp.parse_hgvs_variant(var_g)

var.posedit.pos.start is var.posedit.pos.end
```
`>>>True`
```python
var_g = 'NC_000001.10:g.1647893_1647894delinsCTTTCTT'

var = hp.parse_hgvs_variant(var_g)

var.posedit.pos.start is var.posedit.pos.end
```
`>>>False`


I think the start and end position should always be two different instances no matter the start and end positions are equal or not.

**Comment by ianfab** [comment]
Thanks a lot for the quick reply and fix.
