### ISSUE TITLE
Miss alignment or a transcript in UTA

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [biocommons/hgvs#475]
Hi Reece and co,

I have been trying to map NW_003315905.1:g.133179_133180delAG onto transcript NM_020699.2. Accurate mapping would produce NM_020699.2:c.1010_1011delCT, but I'm getting NM_020699.2:c.803+1_804-1delCT.

I did some digging and I believe that the alignment data in UTA is incorrect for this g. c. combination.

according to ftp://ftp.ncbi.nih.gov/refseq/H_sapiens/alignments/GCF_000001405.33_knownrefseq_alignments.gff3 and ftp://ftp.ncbi.nih.gov/refseq/H_sapiens/alignments/GCF_000001405.25_knownrefseq_alignments.gff3 

NW_003315905.1              RefSeq   cDNA_match       132974  133289  316         -               .               ID=9e88792b-4d42-4160-a66c-8b7b8353b561;Target=NM_020699.2 1145 1460 +;gap_count=0;identity=0.967772;idty=1;num_ident=7237;num_mismatch=0;pct_coverage=96.7772;pct_identity_gap=100;pct_identity_ungap=100

NW_003315905.1:g.133179_133180delAG should map between NM_020699.2.**n.**1145_1460 (NW_003315905.1:g.132974_133289)

According to UTA (accessed via get_tx_exons)  uta_20171026

['GATAD2B', 'NM_020699.2', 'NW_003315905.1', 'splign', -1, 5, 973, 1144, 132973, 133289, '1I1X4=1D3=1D2=1X2=1X2=6I5=1I2=1D3=1X1=1X1=1D1=1X2=1X3=1I1=1I1=1X3=4I3=6I2=1X2=13I1=1X3=3I4=2X1=1X1=1I3=2I1=2I1=2X6=1I3=8I3=8I5=1X1=1I4=4I2X3=1I1=2I3=6I2=4I3=5I5=11I3=8I2=6I3=1I1X2=7I2=1I1=7I3=1X1=1X1=5I2=3I4=10I3=4I1=2D2=1I1X2=5I2=1D3=2X2=1X2=2I1=', None, None, 103671, 228389, 994393, 2243333, 2506709]

NM_020699.2:c.1010_1011delCT maps between NM_020699.2.**n.**973_1144 (NW_003315905.1:g.132973_133289)

It looks like UTA potentially has an exon annotation missing. 
NW_003315905.1              RefSeq   cDNA_match       134073  134243  171         -               .               ID=9e88792b-4d42-4160-a66c-8b7b8353b561;Target=NM_020699.2 974 1144 +

Cheers

Pete

**Comment by reece** [comment]
Summary: This will be resolved transparently when UTA is next released.

I haven't investigated this case specifically, but I have seen similar cases before when NCBI updates the alignment *for the same transcript and genome accessions and versions*. Discrepancies are usually on exon boundaries, and occur when the alignment is atrocious anyway. Presumably, the cause is subtle tuning of iterations of splign or perhaps the post-alignment selection process that NCBI uses. The details of that process are fluid and not public, AFAIK.

Look at the CIGAR you provided -- you don't want to use that alignment anyway!

Yes, mutable alignments like this mean that you can't trust projections in these regions.

Several years ago I proposed to NCBI and HGVS that we generate digests for the alignments themselves. That is, we treat alignments as first class entities so that (transcript, genome) accession pairs might actually have multiple alignments. (UTA uses a form of this idea already. If you find a transcript like NM_0123.4/0a419f, it means that the alignment changed and the hash becomes part of the name so that it's distinguishable from the current version.)

**Comment by PeteCausey-Freeman** [comment]
Thanks for the feedback. Interesting information.

It might be worth noting that the alignment comes from the Personalis truth set, so relates to one of the other issues.

Cheers

Pete
________________________________
