### ISSUE TITLE
Adding support for Refseq record versions

### ISSUE THREAD

**Issue by h-joshi** [biocommons/hgvs#521]
Hi,
    I'm using
- hgvs 1.1.3
- seqrepo 2017-11-18

When attempting to convert this to genomic coordinates (NM_000018.**2**:c.1269+3G>A), I get an error: _No alignments for NM_000018.2 in GRCh37 using splign_

NM_000018.**2**:c.1269+3G>A is however accepted.

Is it feasible to add support for handling Refseq record versions? Variants in a clinical context don't necessarily adhere to the latest version and it's non-trivial to amend these records manually.

**Comment by reece** [comment]
UTA *does* contain multiple versions of transcripts (with alignments to multiple references and multiple alignment methods). The problem is that NCBI does not provide historical transcript alignments, and the UTA project started in 2014 after the .2 version was obsoleted. 

You can see this is the RefSeq record at https://www.ncbi.nlm.nih.gov/nuccore/NM_000018.2:
```
COMMENT     REVIEWED REFSEQ: This record has been curated by NCBI staff. The
            reference sequence was derived from AL536186.3, BI822737.1,
            BC012912.1 and AA643658.1.
            This sequence is a reference standard in the RefSeqGene project.
            [WARNING] On Jul 7, 2012 this sequence was replaced by NM_000018.3.
            On Sep 28, 2005 this sequence version replaced NM_000018.1.
```

I get this question a few times a year, so just added it to the [FAQ](https://hgvs.readthedocs.io/en/latest/faq.html). Would you please read that and provide feedback about clarity?

**Comment by reece** [comment]
@h-joshi: Please see previous comment and provide feedback.

**Comment by h-joshi** [comment]
Hi Reece, Thanks! This definitely why some transcripts won't ever be covered. I also imagine that this'll be a diminishing issue over time.
