### ISSUE TITLE
hgvs requires pysam via seqrepo; dependency should be optional

### ISSUE THREAD

**Issue by khmccurdy** [biocommons/hgvs#522]
In my brief research, I came across a pysam fork designed to run on Windows: https://pypi.org/project/pysam-win/ (in reference to #470 )
I have not had the opportunity to test it yet, and likely will not have the ability to compare the two libraries myself, but I believe this may be worth investigating in the interest of expanding OS compatibility.

**Comment by reece** [comment]
Thanks, Kevin.

There are two things going on here. pysam is getting pulled in by seqrepo, which really should be optional (#523).

The second is issue you've identified regarding pysam on windows. Given that the challenge is really with seqrepo, would you please create a new issue in that repo, reference it in this hgvs issue, and then close it here?

Thanks!

**Comment by khmccurdy** [comment]
Issue moved to https://github.com/biocommons/biocommons.seqrepo/issues/32.

**Comment by reece** [comment]
Status: hgvs currently *requires* seqrepo, which in turn requires pysam. That means that it's impossible to install hgvs without installing pysam.

Plan: make seqrepo *optional* in hgvs (with `extras_require`). This will create a breaking change because current users of hgvs with seqrepo will now have to specify seqrepo manually on installation.

**Comment by khmccurdy** [comment]
If it works within the confines of a setup program, Python has the ability to check which OS it's running in. Maybe the setup could consider seqrepo required or optional depending on whether it's on Windows?
