### ISSUE TITLE
c_to_p fails for NM_001256125.1:c.1015_1016insAGGGACTGGGCGGGGCCATGGTCT

### ISSUE THREAD

**Issue by andreas-invitae** [biocommons/hgvs#525]
Hi,

The following variant fails c_to_p:

```python
        hgvs = "NM_001256125.1:c.1015_1016insAGGGACTGGGCGGGGCCATGGTCT"
        var_c = parser.parse_hgvs_variant(hgvs)
        var_p = vm.c_to_p(var_c)
```
with the following stacktrace:
```
  File "/usr/local/lib/python2.7/dist-packages/hgvs/variantmapper.py", line 359, in c_to_p
    var_p = builder.build_hgvsp()
  File "/usr/local/lib/python2.7/dist-packages/hgvs/utils/altseq_to_hgvsp.py", line 143, in build_hgvsp
    var_ps = [self._convert_to_sequence_variants(x, self._protein_accession) for x in variants]
  File "/usr/local/lib/python2.7/dist-packages/hgvs/utils/altseq_to_hgvsp.py", line 180, in _convert_to_sequence_variants
    aa_start = aa_end = AAPosition(base=start, aa=deletion[0])
IndexError: string index out of range
```

Any thoughts? 
Thanks,

Andreas

**Comment by ianfab** [comment]
The issue seems to be that the variant results in a proper insertion on the protein level starting with a stop codon. For debugging purposes I inserted
```
                    if not diff_indices and not deletion and insertion[0] == '*':
                        diff_indices.append(0)
```
before line [hgvs/utils/altseq_to_hgvsp.py:117](https://github.com/biocommons/hgvs/blob/master/hgvs/utils/altseq_to_hgvsp.py#L117) in order to keep at least one reference amino acid for insertions that start with a stop codon. Then I get `NP_001243054.2:p.(Trp339Ter)`, which looks good to me. I hope this helps to find a proper fix.

**Comment by andreas-invitae** [comment]
Thanks for the quick fix!

**Comment by reece** [comment]
Yep, I had concluded the same cause (insertion of in-frame Ter) but hadn't worked out the fix.
Thanks for solving the problem for us! I incorporated your proposed change with tests and will release in a couple of hours.
