### ISSUE TITLE
Change default normalizer shuffle direction to 5`

### ISSUE THREAD

**Issue by nathanmadams** [biocommons/hgvs#561]
It's more typical to left-align during normalization where "left" means "the 5` end".

**Comment by PeteCausey-Freeman** [comment]
Hi Nathan

VCF 5' normalizes, HGVS 3' normalizes. Please refer to the HGVS guidelines under 3' rule 
[http://varnomen.hgvs.org/recommendations/general/](http://varnomen.hgvs.org/recommendations/general/). In terms of HGVS variant descriptions, the are certainly not commonly 5' normalized otherwise they are not valid.

**Comment by nathanmadams** [comment]
Thanks Peter! I just realized that mistake myself (from reading https://www.biostars.org/p/150690/) and when I came back here to delete the ticket you had already responded. Apologies for the confusion. Today I learned...
