### ISSUE TITLE
allele information not available for dup

### ISSUE THREAD

**Issue by deannachurch** [biocommons/hgvs#581]
When parsing this line: NM_007194.4(CHEK2):c.1164dup

Things work OK, until I try to get the REF and ALT alleles- which have no value:

```
print("DUP V3: %s\t%s\t%s" % (v3, v3.posedit.pos.start, v3.posedit.edit.ref))
DUP V3: NM_007194.4(CHEK2):c.1164dup	1164
```
Translating to genomic coordinates doesn't help.
is it possible to get this information somehow?

**Comment by reece** [comment]
hgvs models the HGVS as represented. It's not intended to be a general model of variation. (See https://vr-spec.readthedocs.io/ for that!)

So, because the dup didn't specify the reference, the model doesn't have it either by default.

However, you can force it with something like this:
```
>>> import hgvs.edit                                                                                                                                                           
>>> var_c = hp.parse("NM_007194.4(CHEK2):c.1164dup")                                                                                                                           
>>> if isinstance(var_c.posedit.edit, hgvs.edit.Dup): 
...     am38._replace_reference(var_c) 
>>> var_c.posedit.edit.ref                                                                                                                                                     
'C'
```

The reason this isn't filled by default is that it requires a database lookup, which can be expensive. 

I think this really comes back to the fact that the hgvs data model is really for modeling HGVS expressions, not for variant manipulation. These are the same thing in the vast majority of cases, but not when you hit the various shorthand notations in HGVS like dup, inv, conv, etc, for which a general variant model is not well-suited.

**Comment by deannachurch** [comment]
Makes sense- and thanks for the explanation!
