### ISSUE TITLE
Question: Can the HGVS package tell you the distance to the farther exon/intron boundary?

### ISSUE THREAD

**Issue by akeeeshi** [biocommons/hgvs#588]
As I currently use the the hgvs package I can utilize the code below to figure how close an intronic variant is to the closer exon/intron boundary. For this variant it would be 108 bps away. 

`hgvs_g = NC_000007.13:g.128848800C>T`

`hp = hgvs.parser.Parser()
var_g = hp.parse_hgvs_variant(hgvs_g)`

`hdp = hgvs.dataproviders.uta.connect()
am = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name='GRCh37', alt_aln_method='splign', replace_reference=False)`

`var_c = am.g_to_c(var_g, 'NM_005631.4')`

`var_c.posedit.pos.start.offset`
`[1] 108`

Is there a way to do this sort of calculation to find out the distance to the further intron/exon boundary. I believe for this variant it would be 329 bps to the further boundary.

**Comment by reece** [comment]
Not directly. 

The hgvs package follows the guidelines which stipulate that an intronic variant  must be located with the respect to the nearer exon. So, it should also choose the closer one. (I can't remember what happens in ties.)

If you really want to know where they are, I think you'll have to do a couple of projections to probe it. First, project with `g_to_c`. Then perform several projections c_to_g relative to the c. start.

There is a more sophisticated route using the AlignmentMapper with locations (rather than synthesized variants), but that's more than I can describe here. You'll have to suss it out from code.
