### ISSUE TITLE
bioconda recipe? 

### ISSUE THREAD

**Issue by lincoln-harris** [biocommons/hgvs#604]
are there plans to add `hgvs` to [bioconda](https://bioconda.github.io/) or [conda-forge](https://conda-forge.org/)? 
would be pretty straight forward to do: https://github.com/bioconda/bioconda-recipes

could potentially make installs easier, and would open up conda recipes for packages that depend on `hgvs`, see https://github.com/czbiohub/cerebra/issues/92

I tried doing this myself, if you want to take a look: https://github.com/bioconda/bioconda-recipes/pull/23259. I was running into linux install issues with `biocommons.seqrepo` and `psycopg2-binary`...maybe you have thoughts on how to get this working? 

thanks!

**Comment by reece** [comment]
Thanks for giving it a shot. I don't use conda, so don't have the personal motivation for that particular solution.

I have a couple of disconnected thoughts:
* My understanding is that conda can typically rely on packages from pypi. So, it's not clear to me that there's any value in having both conda and pypi packages. "Typically" fails in this case because of the external dependency on libpq, which is outside the realm of pypi.
* #603 suggests using a pure python postgresql library, such as asyncpg or pg8000.
* #199 suggests making the data provider dependencies optional. In practice, that would mean that hgvs would raise import failures at runtime rather than prerequisite failures on installation.
* #199 also suggests implementing a REST interface for UTA and seqrepo. This is already done for seqrepo  (https://github.com/biocommons/seqrepo-rest-service). UTA is outstanding.

My preference would be to migrate all data dependencies to REST interfaces. The complexity of dependencies could then be relegated to people who install those services, or, better, a docker image that does it.

Stepping back to your problem: Do you agree that having a pure REST interface to data would enable us to drop the dependencies that prevent pypi packages from working, and therefore simplify use within conda?

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
