### ISSUE TITLE
 VariantMapper couldn't map variant, AssemblyMapper could

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [biocommons/hgvs#615]
I'm not sure if it's an issue or not.
I was trying to map my database of hgvs coding variants to genomic.

![image](https://user-images.githubusercontent.com/49416765/120241761-d6f16200-c239-11eb-9417-c819176be80f.png)
![image](https://user-images.githubusercontent.com/49416765/120241872-086a2d80-c23a-11eb-88d4-8cfccdea2494.png)
![image](https://user-images.githubusercontent.com/49416765/120241901-16b84980-c23a-11eb-90e8-4e5d4ab197b3.png)

**Comment by reece** [comment]
@AgustinRamiroDiaz : I apologize for the long delay. I didn't see this question earlier.

In the c_to_g line, you're telling hgvs to map a variant on NM_007294.3 to NC_000001.10. There is no such alignment because BRCA1 is on chromosome 17. 

I advise you to use the AssemblyMapper, which will handle these issues for you.
