### ISSUE TITLE
Using Gene symbol hgvs notation

### ISSUE THREAD

**Issue by arpanda** [biocommons/hgvs#637]
I have variants using gene symbol notation. Example: `ARID1A:c.303dupG`. I tried to look at the documents to convert such notation to hgvs `p type` or `g type`. But could not find any such documents. 

So, is it possible? if yes, could you please show an example or documentation link.

Thanks
Arijit

**Comment by reece** [comment]
See misc/experimental/hgvs-guess-plausible-transcripts in the repo.

Using a gene name instead of a sequence accession is common in some communities, but it's not legitimate HGVS and, more importantly, it's totally useless for reliably conveying variant information.

If you're receiving those variants from other places, ask the data source to provide valid HGVS. If you're generating them, please switch to reporting on sequences.
