### ISSUE TITLE
Dup should have an alt when available

### ISSUE THREAD

**Issue by nh13** [biocommons/hgvs#638]
Related to #581.

If we have `DUMMY:c.2_4dupATC`, then I was expecting the [`Dup` class](https://github.com/biocommons/hgvs/blob/9386562cd7c61b7f6ec6c556adcd99e3dfffaa62/hgvs/edit.py#L399) to have both a `ref` AND `alt` defined. Currently, it only has `ref` defined.  

The HGVS recommendation is not to include the duplicated bases, so in that case the current code has `ref` be `None`, but when the duplicated bases are included `ref` is properly stored.  To save space, `alt` could just be:

```python
@property
def alt(self):
    return self.ref * 2
```

What to folks think?

**Comment by reece** [comment]
I'm open to this idea, but it opens up a much larger issue for a few design principles:

- Distinguish parsing (syntactic correctness) from validation. It is intentionally possible (and practically necessary) to be able to parse and emit syntactically correct but semantically broken HGVS expressions because they occur in the wild. For example, ref mismatches and invalid location ranges are parsed but invalid.
- An implication of the above is that an hgvs object instance might be incorrect or incomplete (e.g., missing an optional ref sequence).
- Data lookups are expensive (especially if remote sources are used), and so should not be implicit. Validation, reference correction, etc are expected to be explicit operations.
- And, relevant for this issue, don't implicitly fetch data in order to format an expression.

For this proposal, we need to consider what happens when ref is not provided. (And, in fact, excluding the ref sequence is actually preferred by many on the HGVS committee because it's redundant information.)

```
>>> v = parse("DUMMY:c.2_4dupATC")
>>> v.posedit.edit.ref
'ATC'
>>> v = parse("DUMMY:c.2_4dup")
>>> v.posedit.edit.ref
''
```

Clearly, `ref * 2` will be plainly wrong in this case, and it's a significant (and perhaps even majority) use case.

Variants do have a `fill_ref()` method to make this easier, like so:

```
>>> v = parse("NM_000314.4:c.2_4dup")
>>> v.fill_ref(hdp)
SequenceVariant(ac=NM_000314.4, type=c, posedit=2_4dup, gene=None)
>>> v.posedit.edit.ref
'TGA'
```

I don't have an easy solution to handle the proposed `alt` method without either 1) adopting a new implicit behavior and setting a global data provider, or 2) requiring that the user `fill_ref()` before calling `alt`, which means that we also need to handle the case when they don't do so.

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
